"""Apply deterministic NAS metadata to RAGFlow documents.

Run inside the RAGFlow container with `/ragflow` as working directory.

The script reads the upload report generated by ragflow_upload_manifest_batch.py
and writes stable document metadata through DocMetadataService. It does not
upload, parse, or re-embed documents.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any

from api.db.services.doc_metadata_service import DocMetadataService
from common import settings
from business_metadata import infer_business_metadata


REPORT_PATH = Path(os.getenv("RAGFLOW_UPLOAD_REPORT_PATH", "/tmp/ragflow_upload_manifest_report.json"))
OUT_PATH = Path(os.getenv("RAGFLOW_METADATA_REPORT_PATH", "/tmp/ragflow_hard_metadata_report.json"))
LOG_PATH = Path(os.getenv("RAGFLOW_METADATA_LOG_PATH", "/tmp/ragflow_hard_metadata.log"))
DRY_RUN = os.getenv("RAGFLOW_METADATA_DRY_RUN", "0").lower() in {"1", "true", "yes", "y"}

HARD_KEYS = {
    "knowledge_base",
    "knowledge_base_name",
    "permission_group",
    "permission_groups",
    "source_system",
    "nas_abs_path",
    "nas_root_name",
    "nas_relative_path",
    "nas_parent_path",
    "nas_top_folder",
    "nas_path_hash",
    "nas_mtime",
    "nas_mtime_epoch",
    "file_ext",
    "file_size_bytes",
    "file_size_mb",
    "doc_year",
    "year",
    "month",
    "season",
    "model",
    "models",
    "document_type",
    "business_version",
    "business_scope",
    "business_metadata_version",
    "business_metadata_source",
    "authority_level",
    "authority_technical",
    "authority_price",
    "authority_sales_cost",
    "authority_policy_version",
    "upload_batch",
    "metadata_batch",
    "ragflow_upload_status",
    "last_seen_at",
}


def now_text() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def log(message: str) -> None:
    line = f"[{now_text()}] {message}"
    print(line, flush=True)
    with LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(line + "\n")


def write_report(report: dict[str, Any]) -> None:
    OUT_PATH.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")


def infer_doc_year(relative_path: str, filename: str) -> str:
    text = f"{relative_path}/{filename}"
    for match in re.finditer(r"(?<!\d)(20[0-3]\d)(?!\d)", text):
        return match.group(1)
    return ""


def first_path_part(relative_path: str) -> str:
    parts = [p for p in Path(relative_path).parts if p not in {"", "."}]
    return parts[0] if parts else ""


def safe_stat(path_text: str) -> dict[str, Any]:
    if not path_text:
        return {}
    path = Path(path_text)
    try:
        stat = path.stat()
    except OSError:
        return {}
    metadata = {
        "mtime_epoch": int(stat.st_mtime),
        "mtime": datetime.fromtimestamp(stat.st_mtime).isoformat(timespec="seconds"),
        "size": int(stat.st_size),
    }


def build_hard_metadata(item: dict[str, Any], upload_report: dict[str, Any]) -> dict[str, Any]:
    nas_path = str(item.get("nas_path") or "")
    filename = str(item.get("filename") or "")
    relative_path = str(item.get("relative_path") or filename)
    rel_parent = str(Path(relative_path).parent)
    if rel_parent == ".":
        rel_parent = ""

    kb_key = str(item.get("kb_key") or "")
    stat = safe_stat(nas_path)
    size = int(stat.get("size") or item.get("size") or 0)

    root_name = ""
    if nas_path:
        try:
            parts = Path(nas_path).parts
            if "LE_TOUCH_SHR" in parts:
                idx = parts.index("LE_TOUCH_SHR")
                if len(parts) > idx + 1:
                    root_name = parts[idx + 1]
        except ValueError:
            root_name = ""

    return {
        "knowledge_base": kb_key,
        "knowledge_base_name": item.get("knowledge_base") or "",
        "permission_group": kb_key,
        "permission_groups": [kb_key] if kb_key else [],
        "source_system": "nas_nfs",
        "nas_abs_path": nas_path,
        "nas_root_name": root_name,
        "nas_relative_path": relative_path,
        "nas_parent_path": rel_parent,
        "nas_top_folder": first_path_part(relative_path),
        "nas_path_hash": hashlib.sha256(nas_path.encode("utf-8")).hexdigest()[:16] if nas_path else "",
        "nas_mtime": stat.get("mtime"),
        "nas_mtime_epoch": stat.get("mtime_epoch"),
        "file_ext": Path(filename).suffix.lower(),
        "file_size_bytes": size,
        "file_size_mb": round(size / 1024 / 1024, 3) if size else 0,
        "doc_year": infer_doc_year(relative_path, filename),
        "upload_batch": upload_report.get("batch_name") or "",
        "metadata_batch": datetime.now().strftime("%Y%m%d_%H%M%S"),
        "ragflow_upload_status": item.get("status") or "",
        "last_seen_at": now_text(),
    }
    metadata.update(infer_business_metadata(relative_path, kb_key=kb_key))
    return metadata


def merge_metadata(existing: dict[str, Any], hard: dict[str, Any]) -> dict[str, Any]:
    merged = dict(existing or {})
    for key in HARD_KEYS:
        merged.pop(key, None)
    merged.update(hard)
    return merged


def main() -> None:
    LOG_PATH.write_text("", encoding="utf-8")
    log("init ragflow settings")
    settings.init_settings()

    if not REPORT_PATH.exists():
        raise RuntimeError(f"upload report not found: {REPORT_PATH}")

    upload_report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    report: dict[str, Any] = {
        "started_at": now_text(),
        "finished_at": None,
        "dry_run": DRY_RUN,
        "upload_report_path": str(REPORT_PATH),
        "output_path": str(OUT_PATH),
        "total_files": 0,
        "updated": 0,
        "skipped": 0,
        "errors": [],
        "by_kb": {},
        "samples": [],
    }
    write_report(report)

    tenant_id = upload_report.get("tenant_id") or ""
    if not tenant_id:
        raise RuntimeError("tenant_id missing from upload report")

    kb_ids = {
        kb.get("kb_key"): kb.get("id")
        for kb in upload_report.get("final_state", [])
        if kb.get("kb_key") and kb.get("id")
    }
    index_name = DocMetadataService._get_doc_meta_index_name(tenant_id)
    if not DRY_RUN and not settings.docStoreConn.index_exist(index_name, ""):
        created = settings.docStoreConn.create_doc_meta_idx(index_name)
        if created is False:
            raise RuntimeError(f"failed to create metadata index: {index_name}")

    files = upload_report.get("files") or []
    items_by_kb: dict[str, list[dict[str, Any]]] = {}
    for item in files:
        report["total_files"] += 1
        kb_key = item.get("kb_key") or "unknown"
        if not item.get("document_id"):
            kb_stats = report["by_kb"].setdefault(kb_key, {"updated": 0, "skipped": 0, "errors": 0})
            report["skipped"] += 1
            kb_stats["skipped"] += 1
            continue
        items_by_kb.setdefault(kb_key, []).append(item)

    for kb_key, kb_items in items_by_kb.items():
        kb_id = kb_ids.get(kb_key)
        kb_stats = report["by_kb"].setdefault(kb_key, {"updated": 0, "skipped": 0, "errors": 0})
        if not kb_id:
            report["errors"].append({"kb_key": kb_key, "error": "kb_id_missing_from_upload_report"})
            report["skipped"] += len(kb_items)
            kb_stats["errors"] += len(kb_items)
            continue

        existing_by_doc = DocMetadataService.get_metadata_for_documents(None, kb_id) or {}
        rows: list[dict[str, Any]] = []
        for item in kb_items:
            doc_id = item.get("document_id")
            try:
                existing = existing_by_doc.get(doc_id, {})
                hard = build_hard_metadata(item, upload_report)
                merged = merge_metadata(existing, hard)
                rows.append({"id": doc_id, "kb_id": kb_id, "meta_fields": merged})
                if len(report["samples"]) < 5:
                    report["samples"].append(
                        {
                            "document_id": doc_id,
                            "filename": item.get("filename"),
                            "metadata": hard,
                        }
                    )
            except Exception as exc:
                report["errors"].append({"document_id": doc_id, "filename": item.get("filename"), "error": repr(exc)})
                report["skipped"] += 1
                kb_stats["errors"] += 1

        if DRY_RUN:
            report["updated"] += len(rows)
            kb_stats["updated"] += len(rows)
            log(f"dry-run {kb_key}: prepared={len(rows)} existing_metadata={len(existing_by_doc)}")
            write_report(report)
            continue

        batch_size = int(os.getenv("RAGFLOW_METADATA_BATCH_SIZE", "500"))
        for start in range(0, len(rows), batch_size):
            batch = rows[start : start + batch_size]
            errors = settings.docStoreConn.insert(batch, index_name, kb_id)
            if errors:
                report["errors"].append({"kb_key": kb_key, "stage": "bulk_insert", "start": start, "errors": errors[:20], "error_count": len(errors)})
                report["skipped"] += len(batch)
                kb_stats["errors"] += len(batch)
            else:
                report["updated"] += len(batch)
                kb_stats["updated"] += len(batch)
            write_report(report)
            log(f"bulk {kb_key}: {min(start + len(batch), len(rows))}/{len(rows)} updated_total={report['updated']} errors={len(report['errors'])}")

    if not DRY_RUN:
        refresh_idx = getattr(settings.docStoreConn, "refresh_idx", None)
        if callable(refresh_idx):
            refresh_idx(index_name)

    report["finished_at"] = now_text()
    write_report(report)
    log(f"done, updated={report['updated']}, skipped={report['skipped']}, errors={len(report['errors'])}, report={OUT_PATH}")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
